# Generated by Django 4.1.4 on 2022-12-18 10:14

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productname", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField()),
                (
                    "photo",
                    versatileimagefield.fields.VersatileImageField(
                        blank=True, null=True, upload_to="", verbose_name="Photo"
                    ),
                ),
            ],
        ),
    ]
