# Generated by Django 4.0.7 on 2022-12-20 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='item',
        ),
    ]
